openthread/ot-ns

CONTRIBUTING.md
Travis is not used anymore, however it's still mentioned in documents. 
This PR removes these mentioning.
=> [doc] remove mentioning of Travis

CONTRIBUTING.md, cli/CmdRunner.go, cli/ast.go, cli/runner.go, dispatcher/FailureCtrl_test.go, dispatcher/dispatcher.go, dispatcher/rloc16_map_test.go, dispatcher/send_queue.go, dispatcher/send_queue_test.go, otns_main/otns_main.go, pcap/PcapFile_test.go, progctx/progctx.go, script/common.sh, script/make-pretty, script/pack-web, types/types.go, web/site/bindata.go, web/site/site.go, web/site/site_test.go
Make Go code pretty with script/make-pretty.
=> [pretty] add make-pretty

dispatcher/dispatcher.go
This PR reduced the CPU from 140% to <2% when there is no node.
=> [dispatcher] fix high cpu usage of empty network

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/test.yml, pylibs/unittests/test_signals.py, script/install, script/test, web/web.go
This PR:
- Tune github actions to run builds and tests on macOS
=> [github-actions] run builds and tests on macOS

.github/workflows/test.yml, pylibs/examples/farm.py, pylibs/examples/form_partition.py, pylibs/examples/ping.py, pylibs/examples/simple.py, pylibs/otns/cli/OTNS.py, pylibs/otns/cli/errors.py, pylibs/unittests/test_signals.py, script/test
This PR makes sure each pyOTNS example in pylibs/examples works by running it for several seconds. 
- pyOTNS raises OTNSExitedError with error code when OTNS exits
- handle OTNS exit properly in example scripts
=> [github-actions] make sure pyOTNS examples work

pylibs/otns/cli/OTNS.py, pylibs/unittests/test_basic.py
This PR allows use OTNS in with-statement:
```python
with OTNS() as ns:
...
```
=> [pyOTNS] OTNS support with statement

.gitignore
Update the library name ignored by git to reflect the change.
=> [gitignore] fix pylib name

script/install, script/utils.sh
script/install failed once in while in GitHub actions when `go get ./cmd/otns`
This PR repeat  `go get ...` for 3 times for stability.
=> [scripts] go get repeat 3 times for install

dispatcher/dispatcher.go
This PR tries to fix issues in `transmit` event visualization we have observed.
=> [visualization] fix transmit event visualization

otns_main/otns_main.go, simulation/node.go, simulation/node_config.go, simulation/simulation_config.go
This PR allows `OTNS` to search for the `ot-cli` executable in $PATH.
=> [ot-cli] search for ot-cli executable in $PATH

dispatcher/dispatcher.go
This PR allows setting speed for real devices. 
@ctan-g 
I believe this PR should be enough for adjusting play speed for `Silk Log Replay`.
=> [real] allow set speed in real mode

go.mod, script/check-pretty, script/make-pretty, script/setup-dev
This PR checks and tidy go.mod.
=> [style] check go.mod pretty

.github/workflows/stress.yml, pylibs/otns/cli/OTNS.py, pylibs/stress_tests/commissioning.py, pylibs/unittests/OTNSTestCase.py, pylibs/unittests/test_basic.py
This stress test makes sure that commissioning can eventually succeed in a lossy network.
=> [stress-tests] add commissioning stress test

pylibs/unittests/test_basic.py
Add a new test for adding node with ID.
=> [tests] Add test add node with ID

.github/workflows/develop.yml, script/setup-dev
This PR adds the `Develop` workflow to verify development related scripts work.
=> [github-actions] add Develop workflow

.github/workflows/stress.yml, cli/CmdRunner.go, dispatcher/Node.go, dispatcher/dispatcher.go, pylibs/stress_tests/BaseStressTest.py, pylibs/stress_tests/ping_latency.py, types/types.go, visualize/grpc/grpcField.go, visualize/grpc/grpcNode.go, visualize/grpc/grpcVisualizer.go, visualize/multi/multiVisualizer.go, visualize/types.go
Test setup:
- 12 routers ping each other to measure the ping delay of different hops and different data size
- Topology
- 6 routers form circle I
- 6 routers form circle II
- Fault Injections: none
- Pass Criteria
- ping delay < 100ms
=> [stress-tests] add ping latency stress test

pylibs/otns/cli/OTNS.py, pylibs/stress_tests/BaseStressTest.py, pylibs/stress_tests/errors.py, pylibs/stress_tests/service_connectivity.py
Test setup:
- Nodes pings the BR by it's service ALOC and measure the connectivity
- Topology
- Router x20
- FED x10
- MED x10
- SED x10
- Fault Injections:
- Nodes are constantly moving
- Nodes fail for 60s in every 600s
- Packet Loss Ratio set to 0.2
- Pass Criteria
- Max Delay (of all nodes) <= 3600s
=> [stress-tests] add service ALOC connectivity stress test

.github/workflows/docker.yml, etc/docker/playground/Dockerfile
This PR builds and pushes docker image `openthread/otns:playground`.
Tested locally that it works.
=> [docker] build docker image - playground

simulation/simulation.go
to be more strict on error handling.
=> [simulation] panic if remove tmp file failed

dispatcher/dispatcher.go
Required by https://github.com/openthread/openthread/pull/6476
=> [simulation] use fixed radio frame transmission delay

pylibs/stress_tests/README.md, pylibs/stress_tests/network_forming.py
This commit adds README.md for stress tests.
=> [stress-tests] add README.md

pylibs/otns/cli/OTNS.py, pylibs/stress_tests/commissioning.py, pylibs/unittests/test_commissioning.py, simulation/node.go, simulation/simulation.go, simulation/simulation_config.go
Depends-On: https://github.com/openthread/openthread/pull/6721
=> [network-key] change name from `master` to `network`

pylibs/unittests/test_commissioning.py
=> [unit-test] properly configure operational dataset

etc/docker/playground/Dockerfile
Fixes: https://github.com/openthread/ot-ns/actions/runs/5430297038/jobs/9902976233?pr=504
=> [docker] build openthread using `cmake-build`

script/bootstrap, script/common.sh
See https://www.shellcheck.net/wiki/SC2316
=> [script] replace `export readonly` with `declare -rx`

script/bootstrap
This allows a user to stay up to date using simple 'git pull' followed by 'bootstrap'. If the submodule changed, it's then automatically set to the expected commit. Also any additional submodules that might have been added are auto-initialized.
=> [script] add Git submodule update/init to bootstrap script

prng/prng.go, radiomodel/fading_model.go
Go 1.20 deprecated use of rand.Seed().
=> [rand] avoid use of global random number generator

pylibs/case_studies/large_diagnostics.py, pylibs/case_studies/srp_lease_time.py, pylibs/case_studies/srp_remove_service.py
This adds 3 case studies into the 'case_studies' directory for learning and experimentation. The result of these can be observed in the PCAP files produced.
=> [pylibs] add 3 case studies on SRP and Diagnostics
