pylibs/examples/farm.py
This PR adds the farm example that simulates a farm of horses, which moves and are monitored by sensors.
Run demo quickly:
```bash
cd /path/to/directory/of/ot-cli-ftd
wget https://raw.githubusercontent.com/simonlingoogle/ot-ns/demo/farm/pylibs/examples/farm.py
PYTHONPATH=/path/to/otns/pylibs python3 farm.py
```
=> [examples] add `farm` example

cli/CmdRunner.go, dispatcher/Node.go, dispatcher/dispatcher.go, otns_main/otns_main.go, pylibs/unittests/test_signals.py, script/test
This PR enhance OTNS to handle OS signals gracefully:
- Exit gracefully on signals: TERM, QUIT, INT, HUP
- Ignore signals: ALRM, CHLD
- Add a Python unit test to verify signals are handled properly.
=> [proc] handle OS signals gracefully

script/test
**Get OTNS better suited for [#4847](https://github.com/openthread/openthread/pull/4847)**
This PR allow test script to test with a given OpenThread directory so that we can run the test script for OpenThread CI.
=> [test] allow to specify OT directory in test

otns_main/otns_main.go, pylibs/unittests/test_basic.py, pylibs/unittests/test_signals.py
Ignoring `SIGCHLD` could cause deleting node to block forever on macOS.
#21 has been created to catch bugs on macOS in the future.
=> [simulation] fix deleting node could block forever

cli/CmdRunner.go, cli/README.md, cli/ast.go, dispatcher/dispatcher.go, dispatcher/visualization_options.go, pylibs/examples/farm.py, pylibs/otns/cli/OTNS.py, pylibs/unittests/test_basic.py
This PR:
- Add the `cv` command for configuring visualization options
- Add `OTNS.config_visualization` to `pyOTNS`
- Turn off visualization broadcast messages  in the `farm` demo
=> [visualization] configure visualization options

script/install-deps
`wget` is not available on macOS by default. 
Better to install it in script. 
**This PR is required by the Codelab**
=> [script] install wget before installing dependencies

.github/workflows/test.yml, cli/CmdRunner.go, cli/runner.go, dispatcher/dispatcher.go, otns_main/otns_main.go, pylibs/otns/cli/OTNS.py, pylibs/unittests/OTNSTestCase.py, pylibs/unittests/test_signals.py, script/test, simulation/node.go, simulation/simulation.go
This PR fixes potential blocking issues when terminated:
=> [signals] make sure otns gracefully when terminated

go.mod
Run: 
```bash
$ go get -u all && go mod tidy
```
Decided to update Go modules because this error happens often in GitHub actions:
```bash
go: honnef.co/go/tools@v0.0.1-2019.2.3: unknown revision v0.0.1-2019.2.3
go: error loading module requirements
```
=> [go-mod] update go modules

dispatcher/dispatcher.go
This PR allows dispatcher to receive and handle UDP events even when there is no node. 
**Background:**
- Usually, OTNS creates nodes by itself and expects no UDP event before it starts creating nodes. 
- However, it is possible that user starts an OpenThread instance manually. OTNS should be able to receive UDP events from this instance too.
=> [dispatcher] call recvEvents() when no node

otns_main/otns_main.go, simulation/node.go, simulation/simulation.go, simulation/simulation_config.go
This PR allows specifying OT Cli executable path instead of bin directory.
=> [cmdline] specify OT CLI exe path instead of bin directory

cmd/real/otns-silk-proxy/otns-silk-proxy.go, dispatcher/dispatcher.go, otns_main/otns_main.go, script/install, simulation/node.go, simulation/simulation.go, simulation/simulation_config.go
This PR enhances OTNS to support real devices.
- adds `-real` option which turns on the `Real` mode in which `OTNS` expects the nodes to be real devices. 
- adds `otns-silk-proxy` program to wrap silk devices.
Run OTNS for silk devices:
```
./script/install
otns -raw -real -ot-cli $(which otns-silk-proxy)
```
The major difference between `real` and `simulation` modes are:
- Dispatcher in `real` mode neither receives nor sends `Alarm` and `Radio` events (because they are unnecessary)
- All devices are assumed to be sleeping (not alive), so dispatcher never blocks for receiving UDP events
=> [dispatcher] add real mode for real devices

dispatcher/Node.go, dispatcher/dispatcher.go, dispatcher/event.go
Originally OTNS listens at 127.0.0.1:9000 for UDP events so it must run locally with simulation nodes. 
This PR enhances OTNS to allow it to receive and send UDP events from remote nodes.
The source address of a received UDP event will be used as the peer address for that node.
=> [dispatcher] allow receive UDP events from remote nodes

dispatcher/dispatcher.go
This PR visualizes `transmit` status emitting.
**Background:**
Real devices uses `transmit` status emitting for visualizing messages because they do not send radio events to OTNS. 
OTNS should ignore `transmit` status emitting if not in `real` mode. 
This PR works together with https://github.com/openthread/openthread/pull/5195
=> [visualization] visualize transmit status emitting

.github/workflows/test.yml, dispatcher/dispatcher.go, dispatcher/event.go, otns_main/otns_main.go, pylibs/examples/form_partition.py, pylibs/unittests/OTNSTestCase.py, pylibs/unittests/test_basic.py, pylibs/unittests/test_commissioning.py, pylibs/unittests/test_signals.py, simulation/node.go, simulation/simulation.go, simulation/simulation_config.go
This PR will enhance OTNS to support both virtual time UART and non-virtual time UART. 
- OTNS turns on/off virtual time UART if OS env `VIRTUAL_TIME_UART=1/0`
- Use longer `go` durations for non virtual-time UART to reduce the chance of false fails.
- Run each test for both `VIRTUAL_TIME_UART=1/0`
=> [simulation] support virtual time UART

dispatcher/dispatcher.go
This PR fixes a bug that deleting a node in real mode fails. 
**Should never call `setSleeping` for real devices because they are always sleeping**
=> [real] fix delete node error

cli/CmdRunner.go, cli/runcli/runcli.go, cli/runner.go, cmd/real/otns-silk-proxy/otns-silk-proxy.go
`OTNS Cli` and `otns-silk-proxy` use almost same CLI logic that uses `readline`.
This PR adds a new `runcli` package that encapsulate these logic to reduce duplicated code.
=> [cli] add runcli package for common CLI logic

script/test
Running `./script/bootstrap` for `openthread` often fail when installing `shellcheck`. For example: [log](https://pipelines.actions.githubusercontent.com/yK5b9HpAJKCrbAcBv28ULmQ0nqYkgcTG4HVYvTZeTCAh35Bb7R/_apis/pipelines/1/runs/947/signedlogcontent/18?urlExpires=2020-07-11T16%3A25%3A27.7314832Z&urlSigningMethod=HMACV1&urlSignature=eB%2BJ6ZrTsbGDTZGLiW0FJLvW0hb%2Fxjvha869PVXfnWc%3D).
This PR repeats bootstrapping openthread for multiple times to reduce false fails.
=> [scripts] repeat bootstrap openthread for 3 times

dispatcher/dispatcher.go, otns_main/otns_main.go, simulation/node.go, simulation/simulation.go, simulation/simulation_config.go
This PR enhances OTNS to auto-detect if a node uses virtual time UART, instead of depending on OS env `VIRTUAL_TIME_UART`. 
This PR should allow OTNS to work transparently with OpenThread simulation of both UART types, and even to create nodes of both types at the same time (but it's not tested).
=> [simulation] auto detects whether a node uses virtual time UART

cli/CmdRunner.go, cli/ast.go, pylibs/otns/cli/OTNS.py, simulation/node.go, simulation/node_config.go
This PR allows users to specify a different OT executable when adding nodes instead of the default executable configured by `-ot-cli <executable>`.
=> [cli] allow specify OT executable when adding nodes

dispatcher/dispatcher.go
Some background on why OTNS expects the node to send `extaddr` status right after node being created:
This feature was added when `Virtual Time UART` was supported by #5 
OT Simulation that uses Virtual time UART receives/sends CLI input/output via UDP events, instead of stdin/stdout.
After the node is created, OTNS needs to send CLI commands to it immediately, e.g. `mode rsdn`, `thread start`, etc. But it is likely that the simulation instance has not opened the UDP port for receiving UDP messages and thus the CLI commands could be lost. So, OTNS needs a way to know that the node is ready for receiving UDP messages before sending any CLI commands. A simple and straightforward way of doing this is by receiving any UDP message from the node. 
Since `extaddr` status is the first UDP message …
=> [real] do not wait for extaddr change from real devices

cli/CmdRunner.go, dispatcher/dispatcher.go, otns_main/otns_main.go, simulation/simulation.go, simulation/simulation_config.go, web/site/site.go, web/site/site_test.go, web/web.go
This PR enhances OTNS by adding a new `-listen` argument to specify listening address of OTNS. 
```bash
$ otns -listen localhost:9000
```
```bash
$ otns -listen :9000
$ otns -listen 0.0.0.0:9000
```
```bash
$ otns -listen "0.0.0.0:10000"
```
This also allows us to run multiple OTNS at the same time.
For example, we can run 3 OTNS instances simultaneously:
```
$ PORT_OFFSET=0 otns -listen :9000
$ PORT_OFFSET=1 otns -listen :10000
$ PORT_OFFSET=2 otns -listen :11000
```
=> [dispatcher] allow specify listen address

dispatcher/dispatcher.go, otns_main/otns_main.go, simulation/node.go, simulation/simulation_config.go, threadconst/threadconst.go
This PR enhances OTNS to calculate the correct PORT_OFFSET according to the specified listen address:
Now we don't need to specify PORT_OFFSET for OTNS:
```bash
$ otns -listen :12000  # use PORT_OFFSET=3 automatically 
```
=> [simulation] calculate PORT_OFFSET according to listen addr

.github/workflows/stress.yml, pylibs/stress_tests/BaseStressTest.py, pylibs/stress_tests/StressTestResult.py, pylibs/stress_tests/large_network_forming.py, pylibs/stress_tests/run_stress_suite.py, script/test
This PR adds the `large_network_forming` stress test. 
The stress test creates 8x8 nodes and wait for them to form partitions. 
- Random packet loss is used to make the network not that stable so that corner cases can be checked. 
- The test executes for  10 hours in simulating time (much less in actual time).
- The test passes as long as no node crashes. 
This is one of the tests of #11, but I plan to divide it into multiple PRs to ease code reviewing.  
**This very stress test revealed subtle bugs fixed by https://github.com/openthread/openthread/pull/4860.**
=> [stress-tests] add the large_network_forming stress test

script/test
`form_partition.py` is failing quite often which is annoying for OpenThread CI. 
I tend to skip it for now to make OpenThread CI run smoother. 
Currently there is no clue why it failed yet. Will submit a fix when resolved.
=> [scripts] skip running example form_partition.py

cli/README.md
This commit fixes the issue where Node ID support for `add` CLI command is missing in README.
=> [doc] add id arg to add CLI command README

simulation/node.go
Coverage data was not generated from ot-cli-ftd when running otns. 
Turnout it was due to otns killing ot-cli-ftd using SIGKILL. 
Should use SIGTERM instead.
=> [ot-cli] kill ot-cli process with SIGTERM

web/web.go
This PR kills pre-existing `grpcwebproxy` process so that web visualization works smoothly.
Pre-existing `grpcwebproxy` process could cause new `gprcwebproxy` to quit unexpectedly. In such case, we kill it and restart `grpcwebproxy`.
=> [grpcwebproxy] kills existing process

pylibs/unittests/test_real.py
This commit changes `test_real` so that it waits till OTNS gRPC server is ready in each test's set up method.
=> [unittests] Real mode tests wait for gRPC server to start

dispatcher/dispatcher.go, otns_main/otns_main.go, simulation/simulation.go, simulation/simulation_config.go
This PR adds the `-dump-packets` (default: false) argument to `otns`.
If `-dump-packets` is on, OTNS dumps raw radio packets via STDOUT. 
```
> go 100
DUMP:PACKET:11549279961:1:0B41D8C7CEFAFFFF11346B5760F6710E7F3B01F04D4C4D4C4BE00015A10100000000000001BD8BF63F0A0A6AF8C992C8841A6E3C7EC2827F41B359781FF8ED1028BAC4E5A1FD
DUMP:PACKET:11568497962:2:0B61DC8FCEFA11346B5760F6710EA40ED4AF4305979A7F33F04D4C4D4C2876001547000000000000000149E8EE7BFD307626853CFE5B1F56832FA18AF7828FA174C58F20CA9D2ABC
DUMP:PACKET:11568497963:1:0B12108F43D9
DUMP:PACKET:11568500203:1:0B61DCC8CEFAA40ED4AF4305979A11346B5760F6710E7F33F04D4C4D4C279B0015A201000000000000019654ADA16ED62B9840600A79B232366283E755A80DFD9CDDDC0A306AF7CF
DUMP:PACKET:11568500204:2:0B1210C8F8EF
DUMP:PACKET:11574944125:1:0B41D8C9CEFAFFFF11346B5760F6710E7F3B …
```
=> [dispatcher] dump radio packets to STDOUT

.github/workflows/test.yml, cli/runcli/runcli.go, cli/runner.go, cmd/otns/otns.go, cmd/real/otns-silk-proxy/otns-silk-proxy.go, otns_main/otns_main.go, otnstester/OtnsTest.go, otnstester/tests/consts.go, otnstester/tests/otns_basic_test.go, script/test
This PR adds the `otnstester` and some initial tests. 
**Background:**
In Golang, only Go tests executed as `go test` are able to collect code coverage. Because of it, code coverage of `pyOTNS` tests can not  be measured by `Codecov.io`. 
The `otnstester` wraps the whole `OTNS` program into a Go test so that we can build tests and collect code coverage data for all OTNS functionalities.
=> [otnstester] adds initial otnstester tests

.github/workflows/develop.yml, .github/workflows/lint.yml, .github/workflows/stress.yml, .github/workflows/test.yml
This PR resolves warnings in github actions by disabling homebrew auto update.
=> [github-actions] fix brew update warning

dispatcher/dispatcher.go, otns_main/otns_main.go, simulation/simulation.go
This PR adds two flags:
-  `-no-pcap`: not generate Pcap file
-  `-no-replay`: not generate Replay file
Got this idea when my stress test pcap filled up my whole disk.
=> [flags] add options for less file output

.github/workflows/stress.yml, .github/workflows/test.yml
To fix the `./script/bootstrap` error.
Depends on https://github.com/openthread/openthread/pull/5668
=> [openthread] use latest OT commit

pylibs/otns/cli/OTNS.py, pylibs/stress_tests/BaseStressTest.py, pylibs/stress_tests/mleid_connectivity.py
Test setup:
- Nodes pings the BR by it's MLEID and measure the connectivity
- Topology
- Router x20
- FED x10
- MED x10
- SED x10
- Fault Injections:
- Nodes are constantly moving
- Nodes fail for 60s in every 600s
- Packet Loss Ratio set to 0.2
- Pass Criteria
- Max Delay (of all nodes) <= 3600s
=> [stress-tests] add MLEID connectivity test

.github/workflows/stress.yml, .github/workflows/test.yml, cli/CmdRunner.go, cli/README.md, cli/ast.go, dispatcher/coaps.go, dispatcher/dispatcher.go, go.mod, pylibs/otns/cli/OTNS.py, pylibs/setup.py, pylibs/unittests/test_basic.py, script/install
This PR collects COAP events emitted by OT and provide interfaces for collecting COAP information. 
**This feature can be useful to analyze network performance metrics using COAP messages.**
**Depends on https://github.com/openthread/openthread/pull/5656**
- Process COAP events emitted by OT
- OT CLI: add `coaps` command 
- Enable this feature (disabled by default): `coaps enable`
- Get and purge collected COAP message infos: `coaps` 
- `pyOTNS` add corresponding methods. 
```
> coaps enable
Done
> coaps
- {time: 57019000, src: 2, id: 25421, type: 0, code: 2, uri: a/as, dst_addr: 'fdde:ad00:beef:0:0:ff:fe00:f000', dst_port: 61631, receivers: [{time: 57019961, dst: 1, src_addr: 'fdde:ad00:beef:0:0:ff:fe00:f001', src_port: 61631}]}
- {time: 57019961, src: 1, id: 25421, type: 2, code: 68, …
```
=> [dispatcher] collect COAP events

.github/workflows/stress.yml, pylibs/stress_tests/StressTestResult.py, pylibs/stress_tests/multicast_coaps.py
=> [stress-tests] add CoAP multicast stress test

.github/workflows/stress.yml, pylibs/stress_tests/BaseStressTest.py, pylibs/stress_tests/errors.py, pylibs/stress_tests/otns_performance.py
Test setup:
- Simulate 4x8 nodes at max speed without injected traffic or failure for 1h, measure the execution (real) time.
- Topology
- Router 4x8
- Fault Injections: none
- Pass Criteria
- Execution time <= 30s
The purpose of this test is to measure the performance of OTNS dispatcher and make sure it's not impacted by PRs.
=> [stress-tests] add OTNS benchmark test

.github/workflows/build.yml, .github/workflows/develop.yml, .github/workflows/docker.yml, .github/workflows/lint.yml, .github/workflows/stress.yml, .github/workflows/test.yml, GUIDE.md
OTNS used to support Go 1.11+.
This commit changed OTNS to only support Go 1.13+.
Go 1.13 was released in 2019/09/03, so it has been quite a long time.
=> [go] support go 1.13+

.github/workflows/stress.yml, .github/workflows/test.yml, script/test, visualize/grpc/pb/visualize_grpc.proto
This commit contains necessary changes to make GitHub Actions work again:
- Switch openthread branch from `master` to `main`.
- Switch openthread building from `Makefile` to `cmake`: `script/cmake-build simulation -DOT_OTNS=ON ...`
=> [github-actions] fix checks

script/test
This commit fix openthread build that may cause test failures because cmake-build uses `OT_COVERAGE=ON`.
=> [scripts] fix openthread build

script/test
to fix github action failures (e.g. https://github.com/openthread/openthread/pull/6515/checks?check_run_id=2445158652)
Fixes https://github.com/openthread/openthread/issues/6520
=> [tests] set `OT_COVERAGE=ON` if `COVERAGE=1`

script/test
I've noticed on the [CI logs](https://github.com/openthread/openthread/runs/2483259697#step:6:472), that step `cli-ftd-otns` inside `Simulation 1.1` suite in OpenThread, builds in fact Thread 1.2 version. This PR ensures that `THREAD_VERSION` env is respected.
=> [build] respect the THREAD_VERSION environment variable

pylibs/otns/cli/OTNS.py, pylibs/stress_tests/BaseStressTest.py, pylibs/stress_tests/commissioning.py, pylibs/stress_tests/otns_performance.py, pylibs/stress_tests/service_connectivity.py, script/test
This commit fixes stress tests false passes, and includes other necessary changes to pass stress tests:
- Fixes stress tests false pass
- Fixes several minor test script issues
- Reduces the Joiner threshold to pass commissioning to 99% (used to be 100%)
- Relax `Radio Event` threshold because there are now more `MLE Announce` than before
=> [stress-tests] fix false pass

pylibs/stress_tests/mleid_connectivity.py, pylibs/stress_tests/service_connectivity.py
Seems 20% is too much to pass `connectivity` test suite.
Reduce to 10%
Fixes https://github.com/openthread/openthread/issues/7406
=> [stress-tests] reduce packet loss ratio to 10% for `connectivity`

etc/docker/playground/Dockerfile
The issue is fixed by using golang 1.17. 
I think OTNS does not compile on golang 1.18 yet. 
Will file another PR to fix.
=> [github-actions] fix docker buildx failure

dispatcher/dispatcher.go
Based on the PR [#7500](https://github.com/openthread/openthread/pull/7500), simulated devices will emit their radio state change as a sub event of "Push Status". This commit adds a condition to avoid unnecessary simplelogger's warns when it happens.
=> [dispatcher] receive radio state event of simulated node

pylibs/stress_tests/ping_latency.py
This commit relaxes the check in `ping_latency.py` stress test to 300
msec (from 100 msec). This is to accommodate the "collision avoidance
delay mechanism" which is intended to help prevent self-interference
This mechanism applies a delay after a successful frame tx to a
neighbor which is expected to forward the frame before any next frame
tx.
----
Related to: 
- https://github.com/openthread/openthread/pull/7512
=> [stress-test] relax ping test to allow collision-avoidance delay

.github/workflows/stress.yml, pylibs/stress_tests/128_children.py, script/utils.sh
This commit adds a new stress test to make sure a parent can support up to 128 FED/MED/SED children that all children can successfully attach within a limited duration.
=> [stress-tests] add stress test with 128 children

pylibs/stress_tests/network_forming.py
Fixes https://github.com/openthread/ot-ns/issues/273
Fixes https://github.com/openthread/openthread/issues/7674
=> [stress-tests] remove 7x7 topology from `network_forming.py`

pylibs/stress_tests/commissioning.py, pylibs/stress_tests/network_forming.py, pylibs/stress_tests/otns_performance.py, pylibs/unittests/test_basic.py, pylibs/unittests/test_commissioning.py
This commit increases the wait time for leader start. This is to
address the changes in behavior from Thread 1.3 spec related to the
number of MLE Parent Request messages that device needs to send in
the first attach attempt before it can become leader.  The new design
requires a device to send a total of six Parent Request messages,
first two to routers followed by four to routers and REEDs, each
having its own corresponding wait time.
----
_Background_:
This is in preparation of the upcoming PR in OT which will change the MLE 
attach behavior.
=> [test] increase wait time for leader start

script/install-deps
This should address this warning https://github.com/openthread/openthread/actions/runs/4321875033/jobs/7543625431#step:8:348
This failure is currently blocking https://github.com/openthread/openthread/pull/8829
=> [scripts] add wheel to install_python_libs()

cli/README.md
Simple PR that adds the rfsim 'clkdrift' to docs - parameter code was already there and in OTRFIM platform. Help docs get compiled into the otns binary.
=> [cli] add rfsim 'clkdrift' parameter to docs

pylibs/unittests/test_basic.py, pylibs/unittests/test_commissioning.py
Adds channel check for -ot-script parameter. Adds a commissioning test where a domain name and steering data are used.
=> [pylibs] improve unittest coverage

otns_main/otns_main.go, prng/prng.go
This adds a log line showing the chosen PRNG root seed. This is useful to reproduce a simulation that was run with a random root seed, or time-based root seed selected by OTNS itself.
Resolves https://github.com/openthread/ot-ns/issues/563
=> [prng][main] show PRNG root seed in log output

simulation/node_config.go
Enhances the node auto-placer, which gets used when adding nodes without X/Y/Z coordinate input. When more than 16 End Devices (Children) are added, a new row of End Devices is started. This avoids the End Devices quickly being placed beyond the visible coordinates of the Web GUI.
=> [simulation] node auto-placer places End Devices in rows

ot-rfsim/etc/v11.patch, ot-rfsim/etc/v12.patch, ot-rfsim/etc/v13.patch, ot-rfsim/script/build_v11, ot-rfsim/script/build_v12, ot-rfsim/script/build_v13, script/utils.sh
Increasing the version to 3.5.1, for the mbedtls repo, will support CMake 4.x
=> [ot-rfsim] patch for legacy OT builds - increase CMake version

README.md, etc/docker/playground/run-playground.sh
This fixes the TCP port issue in the playground Docker image, by setting the socket binding host to 0.0.0.0. To address the issue that the web GUI can't be auto-started, a link is displayed which the user can click to open the web GUI. In the README, this Docker image is documented as the quickest way to get started (try-out). Close #650
=> [docker] fix playground Docker port binding and enable manual GUI start

README.md
Add a badge to repo's README file to enable weekly auto refresh in https://deepwiki.com/openthread/ot-ns
=> [docs] add DeepWiki badge link
